site_name: Nob docs
theme:
  favicon: 00_config/favicon.png
  name: material
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nob-islan/documents
  generator: false
copyright: Copyright &copy; nob-islan
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.magiclink
