site_name: Nob docs
theme:
  name: material
  features:
    - content.code.copy
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nob-islan/documents
  copyright: "© nob-islan"
markdown_extensions:
  - codehilite:
      guess_lang: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.magiclink
