site_name: Nob docs
theme:
  name: material
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nob-islan/documents
  copyright: "© nob-islan"
markdown_extensions:
  - codehilite:
      guess_lang: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.magiclink
