[project]
site_name = "Nob docs"
copyright = """
Copyright &copy; nob-islan
"""

[project.theme]
favicon = "00_config/favicon.png"
logo = "00_config/favicon.png"
features = [
    "content.code.copy"
]
variant = "classic"

[[project.theme.palette]]
scheme = "default"
primary = "indigo"
accent = "indigo"
toggle.icon = "lucide/moon"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
primary = "black"
accent = "deep purple"
toggle.icon = "lucide/sun"
toggle.name = "Switch to light mode"

[project.extra]
generator = false

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/nob-islan/documents"

[project.markdown_extensions.pymdownx.highlight]
[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
